import {describeWithMock, drawWithMock} from "./mockBackend";
import {BackendError, type DescribeResponse} from "./interface";

const USE_MOCK_BACKEND = false;

const API_BASE = "http://127.0.0.1:8000";
const DESCRIBE_ENDPOINT = `${API_BASE}/api/describe`;
const DRAW_ENDPOINT = `${API_BASE}/api/draw`;

// upload an image and get the description
export async function describePicture(picture: Blob, _signal?: AbortSignal): Promise<string> {
    console.log("-> [Frontend] Starting describe task at /api/describe...");

    const body = new FormData();
    const fileName = (picture instanceof File && picture.name) ? picture.name : "duck_input.png";
    body.append("image", picture, fileName);

    // 1. Submit image and receive job_id
    const response = await fetch(DESCRIBE_ENDPOINT, {
        method: "POST",
        body,
    });
    await throwIfFailed(response);

    const initData = await response.json();
    const jobId = initData.job_id;
    console.log(`[Duck] Job initiated: ${jobId}. Polling status...`);

    // 2. Poll every 2 seconds until LLaVA finishes
    while (true) {
        await new Promise((resolve) => setTimeout(resolve, 2000));

        const statusRes = await fetch(`${DESCRIBE_ENDPOINT}/status/${jobId}`);
        if (!statusRes.ok) continue;

        const data = await statusRes.json();
        if (data.status === "ready") {
            console.log(`[Duck] Job ${jobId} finished! Fetching text...`);
            break;
        }
        if (data.status === "failed") {
            throw new Error(`Duck description failed: ${data.error || "unknown error"}`);
        }
    }

    // 3. Retrieve description text
    const resultRes = await fetch(`${DESCRIBE_ENDPOINT}/result/${jobId}`);
    await throwIfFailed(resultRes);

    const data = await resultRes.json();
    
    // Explicit fallback in case the interface expected 'description' vs 'text'
    const promptText = data.text ?? data.description;
    
    if (!promptText) {
        console.error("[Duck] Received empty or malformed payload from /api/describe/result:", data);
        throw new Error("Received empty description from backend");
    }

    console.log("[Duck] Output prompt ready for bunny:", promptText);
    return promptText;
}

// request an image generated by text
export async function drawPicture(description: string, _signal?: AbortSignal): Promise<Blob> {
    // 1. Send draw request and receive the job_id JSON
    const response = await fetch(DRAW_ENDPOINT, {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify({text: description}),
    });
    await throwIfFailed(response);

    const initData = await response.json();
    const jobId = initData.job_id;
    console.log(`[Bunny] Job initiated: ${jobId}. Polling status...`);

    // 2. Poll every 2 seconds until status becomes "ready"
    while (true) {
        await new Promise((resolve) => setTimeout(resolve, 2000));

        const statusRes = await fetch(`${DRAW_ENDPOINT}/status/${jobId}`);
        if (!statusRes.ok) continue;

        const data = await statusRes.json();
        if (data.status === "ready") {
            console.log(`[Bunny] Job ${jobId} finished! Fetching generated image...`);
            break;
        }
        if (data.status === "failed") {
            throw new Error(`Drawing generation failed: ${data.error || "unknown error"}`);
        }
    }

    // 3. Download the actual image blob
    const resultRes = await fetch(`${DRAW_ENDPOINT}/result/${jobId}`);
    await throwIfFailed(resultRes);

    const imageBlob = await resultRes.blob();
    if (!imageBlob.type.startsWith("image/")) {
        throw new BackendError(
            "NOT_AN_IMAGE",
            `Expected an image from ${DRAW_ENDPOINT}/result, got "${imageBlob.type}"`
        );
    }

    return imageBlob;
}

// handle error
async function throwIfFailed(response: Response): Promise<void> {
    if (response.ok) return;

    const failure = await response.json().catch(() => null);
    throw new BackendError(
        failure?.error ?? `HTTP_${response.status}`,
        failure?.message ?? response.statusText,
    );
}