import {describeWithMock, drawWithMock} from "./mockBackend";
import {BackendError, type DescribeResponse, type DrawRequest} from "./interface.ts";

const USE_MOCK_BACKEND = import.meta.env.VITE_USE_MOCK_BACKEND;

// API endpoint
const DESCRIBE_ENDPOINT = "/api/describe";
const DRAW_ENDPOINT = "/api/draw";

// upload an image and get the description
export async function describePicture(picture: Blob, signal: AbortSignal): Promise<string> {
    if (USE_MOCK_BACKEND) {
        return describeWithMock(picture, signal);
    }

    const body = new FormData();
    body.append("image", picture, (picture as File).name);

    const response = await fetch(DESCRIBE_ENDPOINT, {method: "POST", body, signal});
    await throwIfFailed(response);

    const {text}: DescribeResponse = await response.json();
    return text;
}

// request an image generated by text
export async function drawPicture(description: string, signal: AbortSignal): Promise<Blob> {
    if (USE_MOCK_BACKEND) {
        return drawWithMock(description, signal);
    }

    const request: DrawRequest = {text: description};
    const response = await fetch(DRAW_ENDPOINT, {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(request),
        signal,
    });
    await throwIfFailed(response);

    const image = await response.blob();
    if (!image.type.startsWith("image/")) {
        throw new BackendError("NOT_AN_IMAGE", `Expected an image from ${DRAW_ENDPOINT}, got "${image.type}"`);
    }
    return image;
}

// handle error
async function throwIfFailed(response: Response): Promise<void> {
    if (response.ok) return;

    const failure = await response.json().catch(() => null);
    throw new BackendError(
        failure?.error ?? `HTTP_${response.status}`,
        failure?.message ?? response.statusText,
    );
}